language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t lbp102/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true lbp102/docker-react npm run test -- --coverage

